name: RFC XML Check

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: dependencies
      run: |
        sudo apt-get install xmllint xml2rfc
    - name: xmllint
      run: xmllint --noout --schema spec/rfc2629.xsd spec/draft-ietf-dtn-tcpclv4.xml
    - name: xml2rfc
      run: make -C spec
