name: RFC XML Check

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: dependencies
      run: |
        sudo apt-get install libxml2-utils xml2rfc
    - name: xml2rfc
      run: make -C spec
